/**
 * Battery icon codepoints (issue #165) - GENERATED by
 * `node scripts/gen_amber_icons.js --battery`. Do not edit by hand.
 *
 * Lucide battery shapes at the canvas stroke weight (1.7), through the same
 * rasteriser as every Amber icon, so they sit in the same family. They have
 * their own fonts and codepoint range - see BATTERY_SYMBOLS in the generator.
 */
#ifndef AMBER_BATTERY_ICONS_H
#define AMBER_BATTERY_ICONS_H

#include "lvgl.h"

LV_FONT_DECLARE(lv_font_amber_batt_16);
LV_FONT_DECLARE(lv_font_amber_batt_24);

#define AMB_BAT_FULL         "\xEE\x84\x80"   // U+E100  bt-full
#define AMB_BAT_MEDIUM       "\xEE\x84\x81"   // U+E101  bt-medium
#define AMB_BAT_LOW          "\xEE\x84\x82"   // U+E102  bt-low
#define AMB_BAT_EMPTY        "\xEE\x84\x83"   // U+E103  bt-empty
#define AMB_BAT_CHARGING     "\xEE\x84\x84"   // U+E104  bt-charging
#define AMB_BAT_WARNING      "\xEE\x84\x85"   // U+E105  bt-warning

#endif // AMBER_BATTERY_ICONS_H
