/**
 * Amber icon codepoints — GENERATED by scripts/gen_amber_icons.js.
 * Do not edit by hand; rerun the generator against the design canvas.
 *
 * The glyphs are the canvas's own SVG icons, rasterised into LVGL fonts, so
 * they are the design's icons rather than the nearest match from an icon set.
 * Use them exactly like the MDI_* defines: set one as a label's text and pick
 * the matching lv_font_amber_* size as its font.
 */
#ifndef AMBER_ICONS_H
#define AMBER_ICONS_H

#include "lvgl.h"
#include "ui_icons.h"   // for the MDI-substituted entries below

LV_FONT_DECLARE(lv_font_amber_16);
LV_FONT_DECLARE(lv_font_amber_24);
LV_FONT_DECLARE(lv_font_amber_32);
LV_FONT_DECLARE(lv_font_amber_40);
LV_FONT_DECLARE(lv_font_amber_wx_32);
LV_FONT_DECLARE(lv_font_amber_wx_64);

#define AMB_IC_CHEV          "\xEE\x80\x80"   // U+E000  ic-chev
#define AMB_IC_CLOCK         "\xEE\x80\x81"   // U+E001  ic-clock
#define AMB_IC_DISPLAY       "\xEE\x80\x82"   // U+E002  ic-display
#define AMB_IC_DOWNLOAD      "\xEE\x80\x83"   // U+E003  ic-download
#define AMB_IC_FOLDER        "\xEE\x80\x84"   // U+E004  ic-folder
#define AMB_IC_GEAR          "\xEE\x80\x85"   // U+E005  ic-gear
#define AMB_IC_GROUPS        "\xEE\x80\x86"   // U+E006  ic-groups
#define AMB_IC_LOCK          "\xEE\x80\x87"   // U+E007  ic-lock
#define AMB_IC_MUSIC         "\xEE\x80\x88"   // U+E008  ic-music
#define AMB_IC_NEXT          "\xEE\x80\x89"   // U+E009  ic-next
#define AMB_IC_PAUSE         "\xEE\x80\x8A"   // U+E00A  ic-pause
#define AMB_IC_PLAY          "\xEE\x80\x8B"   // U+E00B  ic-play
#define AMB_IC_PLUS          "\xEE\x80\x8C"   // U+E00C  ic-plus
#define AMB_IC_PREV          "\xEE\x80\x8D"   // U+E00D  ic-prev
#define AMB_IC_QUEUE         "\xEE\x80\x8E"   // U+E00E  ic-queue
#define AMB_IC_RADIO         "\xEE\x80\x8F"   // U+E00F  ic-radio
#define AMB_IC_REFRESH       "\xEE\x80\x90"   // U+E010  ic-refresh
#define AMB_IC_REPEAT        "\xEE\x80\x91"   // U+E011  ic-repeat
#define AMB_IC_SHUFFLE       "\xEE\x80\x92"   // U+E012  ic-shuffle
#define AMB_IC_SPEAKER       "\xEE\x80\x93"   // U+E013  ic-speaker
#define AMB_IC_STAR          "\xEE\x80\x94"   // U+E014  ic-star
#define AMB_IC_VOL           "\xEE\x80\x95"   // U+E015  ic-vol
#define AMB_IC_WIFI          "\xEE\x80\x96"   // U+E016  ic-wifi
#define AMB_IC_X             "\xEE\x80\x97"   // U+E017  ic-x
#define AMB_SC_CHECK         "\xEE\x80\x98"   // U+E018  sc-check
#define AMB_SC_PAUSE         "\xEE\x80\x99"   // U+E019  sc-pause


#define AMB_WX_CLOUD         "\xEE\x80\x80"   // in lv_font_amber_wx_*
#define AMB_WX_RAIN          "\xEE\x80\x81"   // in lv_font_amber_wx_*
#define AMB_WX_SUN           "\xEE\x80\x82"   // in lv_font_amber_wx_*

#endif // AMBER_ICONS_H
