/**
 * Studio icon codepoints — GENERATED by scripts/gen_studio_icons.js.
 * Do not edit by hand; rerun the generator against the design canvas.
 *
 * The glyphs are the canvas's own SVG icons, rasterised into LVGL fonts, so
 * they are the design's icons rather than the nearest match from an icon set.
 * Use them exactly like the MDI_* defines: set one as a label's text and pick
 * the matching lv_font_studio_* size as its font.
 */
#ifndef STUDIO_ICONS_H
#define STUDIO_ICONS_H

#include "lvgl.h"
#include "ui_icons.h"   // for the MDI-substituted entries below

LV_FONT_DECLARE(lv_font_studio_16);
LV_FONT_DECLARE(lv_font_studio_24);
LV_FONT_DECLARE(lv_font_studio_32);
LV_FONT_DECLARE(lv_font_studio_40);
LV_FONT_DECLARE(lv_font_studio_wx_32);
LV_FONT_DECLARE(lv_font_studio_wx_64);

#define ST_IC_CHEV           "\xEE\x80\x80"   // U+E000  ic-chev
#define ST_IC_CLOCK          "\xEE\x80\x81"   // U+E001  ic-clock
#define ST_IC_DISPLAY        "\xEE\x80\x82"   // U+E002  ic-display
#define ST_IC_DOWNLOAD       "\xEE\x80\x83"   // U+E003  ic-download
#define ST_IC_FOLDER         "\xEE\x80\x84"   // U+E004  ic-folder
#define ST_IC_GROUPS         "\xEE\x80\x85"   // U+E005  ic-groups
#define ST_IC_LOCK           "\xEE\x80\x86"   // U+E006  ic-lock
#define ST_IC_MUSIC          "\xEE\x80\x87"   // U+E007  ic-music
#define ST_IC_NEXT           "\xEE\x80\x88"   // U+E008  ic-next
#define ST_IC_PAUSE          "\xEE\x80\x89"   // U+E009  ic-pause
#define ST_IC_PLAY           "\xEE\x80\x8A"   // U+E00A  ic-play
#define ST_IC_PLUS           "\xEE\x80\x8B"   // U+E00B  ic-plus
#define ST_IC_PREV           "\xEE\x80\x8C"   // U+E00C  ic-prev
#define ST_IC_QUEUE          "\xEE\x80\x8D"   // U+E00D  ic-queue
#define ST_IC_RADIO          "\xEE\x80\x8E"   // U+E00E  ic-radio
#define ST_IC_REFRESH        "\xEE\x80\x8F"   // U+E00F  ic-refresh
#define ST_IC_REPEAT         "\xEE\x80\x90"   // U+E010  ic-repeat
#define ST_IC_SHUFFLE        "\xEE\x80\x91"   // U+E011  ic-shuffle
#define ST_IC_SPEAKER        "\xEE\x80\x92"   // U+E012  ic-speaker
#define ST_IC_STAR           "\xEE\x80\x93"   // U+E013  ic-star
#define ST_IC_VOL            "\xEE\x80\x94"   // U+E014  ic-vol
#define ST_IC_WIFI           "\xEE\x80\x95"   // U+E015  ic-wifi
#define ST_IC_X              "\xEE\x80\x96"   // U+E016  ic-x
#define ST_SC_CHECK          "\xEE\x80\x97"   // U+E017  sc-check
#define ST_SC_PAUSE          "\xEE\x80\x98"   // U+E018  sc-pause

#define ST_IC_GEAR           MDI_COG   // not rasterised - see MDI_SUBSTITUTE

#define ST_WX_CLOUD          "\xEE\x80\x80"   // in lv_font_studio_wx_*
#define ST_WX_RAIN           "\xEE\x80\x81"   // in lv_font_studio_wx_*
#define ST_WX_SUN            "\xEE\x80\x82"   // in lv_font_studio_wx_*

#endif // STUDIO_ICONS_H
